pluginManagement {
    repositories {
        maven {
            name = 'Tencent Forge Plugin'
            url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/'
        }
        maven {
            name = 'Tencent Gradle Plugin'
            url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven/'
        }
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}

rootProject.name = 'dimensionmod'
